version: '3'

networks:
  primary:
    driver: bridge

services:

  grow-controller:
    image: github.com/omnimeta/microponics/grow-controller:local
    build:
      context: grow-controller/
      dockerfile: Dockerfile
    container_name: grow-controller
    tty: true
    restart: 'no'
    environment:
      MICROPONICS_STORAGE_SERVICE_HOST: storage
      MICROPONICS_STORAGE_SERVICE_PORT: 9000
      NODE_NAME: node001
      POD_NAME: pod001
    working_dir: /var/www/grow-controller
    networks:
      - primary
    volumes:
      - ./grow-controller:/var/www/grow-controller
    ports: []
    depends_on:
      - storage

  storage:
    image: github.com/omnimeta/microponics/storage:local
    build:
      context: storage/
      dockerfile: Dockerfile
    container_name: storage
    tty: true
    restart: always
    environment:
       DB_FILE: /var/storage/microponics.sql
    networks:
      - primary
    volumes:
      - ./storage:/var/www/
    ports:
      - 9000:8080

  frontend:
    image: github.com/omnimeta/microponics/frontend:local
    build:
      context: frontend/
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /var/www/
    restart: 'no'
    environment:
      MICROPONICS_STORAGE_SERVICE_HOST: storage
      MICROPONICS_STORAGE_SERVICE_PORT: 9000
    networks:
      - primary
    volumes:
      - ./frontend:/var/www/
    ports:
      - 8094:8080
    depends_on:
      - storage
      - grow-controller
