apiVersion: apps/v1
kind: DaemonSet
metadata:
  {{- if not .Values.growcontroller.nameOverride }}
  name: {{ include "microponics.fullname" . }}-growcontroller
  {{- else }}
  name: {{ include "microponics.fullname" . }}-{{ .Values.growcontroller.nameOverride }}
  {{- end }}
  labels:
    {{- include "microponics.labels" . | nindent 4 }}
  namespace: default
spec:
  selector:
    matchLabels:
      {{- include "microponics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.growcontroller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microponics.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.growcontroller.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # serviceAccountName: {{ include "microponics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.growcontroller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.growcontroller.securityContext | nindent 12 }}
          image: "{{ .Values.growcontroller.image.repository }}:{{ .Values.growcontroller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.growcontroller.image.pullPolicy }}
          env:
            - name: DB_ADDRESS
              value: {{ .Values.ingress.storageHost }}:{{ .Values.frontend.service.port }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat
                - /tmp/health/alive && rm /tmp/health/alive
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - cat
                - /tmp/health/ready && rm /tmp/health/ready
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.growcontroller.resources | nindent 12 }}
          volumeMounts:
            - name: health
              mountPath: /tmp/health
      volumes:
        - name: health
          emptyDir: {}
      {{- with .Values.growcontroller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
