{{- if .Values.ingress.enabled -}}
{{- $fullName := include "microponics.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microponics.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.frontendHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if not .Values.frontend.nameOverride }}
                name: {{ $fullName }}-frontend
                {{- else }}
                name: {{ $fullName }}-{{ .Values.frontend.nameOverride }}
                {{- end}}
                port:
                  number: {{ .Values.frontend.service.port }}
    - host: {{ .Values.ingress.storageHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if not .Values.storage.nameOverride }}
                name: {{ $fullName }}-storage
                {{- else }}
                name: {{ $fullName }}-{{ .Values.storage.nameOverride }}
                {{- end}}
                port:
                  number: {{ .Values.storage.service.port }}
  {{- end }}
