apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if not .Values.storage.nameOverride }}
  name: {{ include "microponics.fullname" . }}-storage
  {{- else }}
  name: {{ include "microponics.fullname" . }}-{{ .Values.storage.nameOverride }}
  {{- end }}
  labels:
    {{- include "microponics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.storage.autoscaling.enabled }}
  replicas: {{ .Values.storage.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microponics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.storage.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microponics.selectorLabels" . | nindent 8 }}
        service: storage
    spec:
      # {{- with .Values.storage.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # serviceAccountName: {{ include "microponics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.storage.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.storage.securityContext | nindent 12 }}
          image: "{{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
          env:
            - name: DB_FILE
              valueFrom:
                secretKeyRef:
                  key: db_filepath
                  name: {{ .Release.Name }}-secrets
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.storage.resources | nindent 12 }}
          volumeMounts:
            - mountPath: "{{ .Values.storage.pathOnContainer }}"
              name: primary-storage
      volumes:
        - name: primary-storage
          persistentVolumeClaim:
            claimName: primary-storage-claim
      {{- with .Values.storage.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storage.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.storage.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
