{{- if .Values.storageingress.enabled -}}
{{- $fullName := include "microponics.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "microponics.labels" . | nindent 4 }}
  {{- with .Values.storageingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.storageingress.tls }}
  tls:
    {{- range .Values.storageingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - http:
        paths:
          - path: /db
            pathType: Prefix
            backend:
              service:
                {{- if not .Values.storage.nameOverride }}
                name: {{ $fullName }}-storage
                {{- else }}
                name: {{ $fullName }}-{{ .Values.storage.nameOverride }}
                {{- end}}
                port:
                  number: {{ .Values.storage.service.port }}
  {{- end }}
