apiVersion: apps/v1
kind: Deployment
metadata:
  {{- if not .Values.growcontroller.nameOverride }}
  name: {{ include "dwc-cluster.fullname" . }}-growcontroller
  {{- else }}
  name: {{ include "dwc-cluster.fullname" . }}-{{ .Values.growcontroller.nameOverride }}
  {{- end }}
  labels:
    {{- include "dwc-cluster.labels" . | nindent 4 }}
spec:
  {{- if not .Values.growcontroller.autoscaling.enabled }}
  replicas: {{ .Values.growcontroller.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dwc-cluster.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.growcontroller.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dwc-cluster.selectorLabels" . | nindent 8 }}
    spec:
      # {{- with .Values.growcontroller.imagePullSecrets }}
      # imagePullSecrets:
      #   {{- toYaml . | nindent 8 }}
      # {{- end }}
      # serviceAccountName: {{ include "dwc-cluster.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.growcontroller.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.growcontroller.securityContext | nindent 12 }}
          image: "{{ .Values.growcontroller.image.repository }}:{{ .Values.growcontroller.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.growcontroller.image.pullPolicy }}
          env:
            - name: "DB_NAME"
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: {{ .Release.Name }}-secrets
            - name: "DB_USER"
              valueFrom:
                secretKeyRef:
                  key: db_user
                  name: {{ .Release.Name }}-secrets
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: {{ .Release.Name }}-secrets
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.growcontroller.resources | nindent 12 }}
      {{- with .Values.growcontroller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.growcontroller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.growcontroller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
