apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  db_name: {{ .Values.secrets.db_name | b64enc }}
  db_user: {{ .Values.secrets.db_user | b64enc }}
  db_password: {{ .Values.secrets.db_password | b64enc }}
  db_root_password: {{ .Values.secrets.db_root_password | b64enc }}
