apiVersion: v1
kind: PersistentVolume
metadata:
  name: primary-storage
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  # can be mounted readwrite by a single node
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: {{ .Values.storage.pathOnHost }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: storage_node
          operator: In
          values:
          - "true"
